version: "3"
services:
  code:
    build: ../builder
    volumes:
      - tao-code:/usr/src/tao

  php-fpm:
    build: ../php-fpm
    depends_on:
      - code
    volumes:
      - tao-code:/var/www/html

  web:
    image: nginx:1.19
    ports:
      - "80:80"
    depends_on:
      - code
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - tao-code:/var/www/html

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_USER: tao
      MYSQL_PASSWORD: tao
      MYSQL_DATABASE: tao

volumes:
  tao-code:
